# Generated by Django 5.1 on 2024-11-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_hold_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='UID',
        ),
    ]
